# Generated by Django 5.2.6 on 2025-09-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0002_moviefile_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("360p", "360p"),
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                            ("4K", "4K"),
                        ],
                        default="720p",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.language",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "subtitle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.moviesubtitle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
